"""initial schema

Creates the four core tables: documents, analyses, clinical_reports,
processing_events. See docs/architecture/system-architecture.md
("Database Design") for the entity-relationship rationale.

Revision ID: 0001
Revises:
Create Date: 2026-09-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('source_type', sa.Enum('TEXT', 'IMAGE', 'PDF', name='document_source_type', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_checksum_sha256', 'documents', ['checksum_sha256'], unique=False)
    op.create_table('analyses',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'EXTRACTING', 'ANALYZING', 'COMPLETED', 'FAILED', name='analysis_status', native_enum=False), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_analyses_document_id_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_created_at', 'analyses', ['created_at'], unique=False)
    op.create_index('ix_analyses_document_id', 'analyses', ['document_id'], unique=False)
    op.create_index('ix_analyses_status', 'analyses', ['status'], unique=False)
    op.create_table('clinical_reports',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('structured_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(length=128), nullable=False),
    sa.Column('ai_model_name', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_clinical_reports_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_reports')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_clinical_reports_analysis_id'))
    )
    op.create_table('processing_events',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('STATUS_CHANGED', 'VALIDATION_FAILED', 'EXTRACTION_STARTED', 'EXTRACTION_COMPLETED', 'EXTRACTION_FAILED', 'AI_ANALYSIS_STARTED', 'AI_ANALYSIS_COMPLETED', 'AI_ANALYSIS_FAILED', 'REPORT_PERSISTED', 'ERROR', name='processing_event_type', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_processing_events_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_events'))
    )
    op.create_index('ix_processing_events_analysis_id', 'processing_events', ['analysis_id'], unique=False)
    op.create_index('ix_processing_events_created_at', 'processing_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_events_created_at', table_name='processing_events')
    op.drop_index('ix_processing_events_analysis_id', table_name='processing_events')
    op.drop_table('processing_events')
    op.drop_table('clinical_reports')
    op.drop_index('ix_analyses_status', table_name='analyses')
    op.drop_index('ix_analyses_document_id', table_name='analyses')
    op.drop_index('ix_analyses_created_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_documents_checksum_sha256', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
